1. What is a Python library? Why we use Python libraries?

Python library is a collection of related functions/ methods that is doing some specific task. Python library provides ready made tools which are nothing but a method/ function. As library is a collection of books, just as python library is a collection of related modules / methods. Bundles of code is there is a python library.

We use python libraries to do various different tasks just by simply importing that required library and calling the ready made methods in it and our task is done.
1) Python libraries provide tools for developers, so developers just use that tools without going into the details and logic of that tool.
2) To make our project easier by just calling the methods.
3) To make our code more readable.
4) To make our code more optimized as libraries have methods more optimized.
5) To increase re_usability. 
6) To make calculations easy for data science related projects.

2. What is the difference between Numpy array and List?

NUMPY ARRAY:
Numpy array is a container to store homogenous data in a contagious memory locations.
1) Numpy array can store only homogenous data.
2) In backened , numpy array actually stores data, not its references.
3) When numpy array is declared, so a fixed size of locations in memory in a contagious manner is allocated to that numpy array which is static not dynamic.
4) Calculations on Numpy array is faster as compared to list because of homogenous data in numpy array and data stored in continous manner.
5) When an item is deleted from Numpy array, so that slot/ location become free or say empty.


LIST:


List is also a container to store hetrogenous data.
1) List stores the hetreogenous data.
2) In backened, list only stores the references of data which is stored somewhere in memory at different locations.list not actually stores data, it stores the hexa_decimal addresses of data.
3) Data is stored at different locations, so data wise it may or may not be stored in contagious manner.
4) References of that data is stored in list in continous manner.
5) When an item is deleted from list, so it is dereferencing the address of that item from list.
6) Calculations on list is slower as compare to Numpy array because list has hetreogenous data and also accessing an item from list takes time.



3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [2]:
import numpy as np
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np.shape(arr1))
print(np.size(arr1))
print(np.ndim(arr1))


(3, 4)
12
2


4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [3]:
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr2[0])

[1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [4]:
arr3 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr3[2][3])

12


6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [32]:
arr4 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr4[0:,[0,2]])
# arr4[row_start : row_stop : step , col_start : col_stop : step]
# print(arr4[0::,0::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [34]:
arr5 = np.random.random((3,3))
print(arr5)

[[0.00138105 0.20198558 0.20865268]
 [0.79700916 0.82800401 0.79629278]
 [0.66261646 0.17928692 0.21183408]]


8. Describe the difference between np.random.rand and np.random.randn?

In [43]:
print("""Example of np.random.rand""")
print(np.random.rand(3,3))
print("""1) np.random.rand print the array in the specified shape having random elements over [0,1] range in uniform distribution""")
print("""Example of np.random.randn""")
print(np.random.rand(3,3))
print("""1) np.random.rand print the array in the specified shape having random elements at [0,1] range in standard normal distribution""")

Example of np.random.rand
[[0.78006147 0.16831452 0.05571849]
 [0.86636207 0.31801284 0.97405519]
 [0.24915037 0.88590921 0.33115091]]
1) np.random.rand print the array in the specified shape having random elements over [0,1] range in uniform distribution
Example of np.random.randn
[[0.18216389 0.13260901 0.31153612]
 [0.82559305 0.54221674 0.772797  ]
 [0.01678364 0.83965612 0.3914392 ]]
1) np.random.rand print the array in the specified shape having random elements at [0,1] range in standard normal distribution


9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [58]:
arr6 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(np.expand_dims(arr6, axis = 0))
print(np.expand_dims(arr6, axis = 0).ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

In [59]:
arr7 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr7.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python:
1) Index wise multiplication
2) Matrix multiplication
3) Add both the matrics
4) Subtract matrix B from A
5) Divide Matrix B by A

In [68]:

Matrix_A2= np.array( [[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
Matrix_B2= np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
# Index_wise multiplication
print(Matrix_A2 * Matrix_B2)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [69]:
# Matrix Multiplication
print(Matrix_A2 @ Matrix_B2.T)

[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [71]:
# Add both the matrics
print(Matrix_A2 + Matrix_B2)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [74]:
# Matrix division
print(Matrix_B2/Matrix_A2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [75]:
# Matrix Subtraction
print(Matrix_B2 - Matrix_A2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


12.  Which function in Numpy can be used to swap the byte order of an array?

In [89]:
arr8 = np.array([[1,2],[4,5]])
print(arr8.byteswap(1))
print("array.byteswap() function is used to swap byte order in numpy")

[[ 72057594037927936 144115188075855872]
 [288230376151711744 360287970189639680]]
array.byteswap() function is used to swap byte order in numpy


13.  What is the significance of the np.linalg.inv function?

In [97]:
print(np.linalg.inv(arr8))
"""np.linalg.inv is inverse method used in matrix calculation present in linear algebra.

    The significance of np.linalg.inv is that it directly takes the inverse of a matrix."""

[[-2.31296463e-17  9.25185854e-18]
 [ 1.85037171e-17 -4.62592927e-18]]


'np.linalg.inv is inverse method used in matrix calculation present in linear algebra.\n\n    The significance of np.linalg.inv is that it directly takes the inverse of a matrix.'

4. What does the np.reshape function do, and how is it used?

In [108]:
arr9 = np.array([[1,2],[3,4],[5,6]])
print("Before reshape")
print(f"{arr9}")
print(f"After Reshape")
print(np.reshape(arr9,(2,3)))

print(f"1) reshape function reshapes the given matrix in to some other given no of rows and columns" )
print(f"2) This reshape function will reshape any matrix but the given no of rows and columns product must be equal to the original matrix( before reshaping)")


Before reshape
[[1 2]
 [3 4]
 [5 6]]
After Reshape
[[1 2 3]
 [4 5 6]]
1) reshape function reshapes the given matrix in to some other given no of rows and columns
2) This reshape function will reshape any matrix but the given no of rows and columns product must be equal to the original matrix( before reshaping)


15. What is broadcasting in Numpy?

1) The ability of numpy to perform arithmatic operations between arrays of different shapes.
2) The shapes must be compatible.
3) If the arrays shapes are compatible , so  numpy will broadcast one of it to another or both of them to some third array.
4) Broadcasting is a powerful mechanism in Numpy, which differentiate Numpy from others.

In [116]:
# Example of Broadcasting
var1 = np.array(np.arange(0,20,2,)).reshape(2,5)
var1

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [119]:
a  = 10
print( var1 + a )
""" var1 is matrix and 'a 'is a simple scalar variable, so by doing addition between them, this scalar is added to each and every element of matrix."""

[[10 12 14 16 18]
 [20 22 24 26 28]]


" var1 is matrix and 'a 'is a simple scalar variable, so by doing addition between them, this scalar is added to each and every element of matrix."

In [122]:
# Example of Braodcasting
var2 = np.arange(3)
var2

array([0, 1, 2])

In [124]:
var3 = np.arange(3).reshape(3,1)
var3


array([[0],
       [1],
       [2]])

In [126]:
print(var2 + var3)
"""Here both var2 and var3 are broadcasted to some other shape"""

[[0 1 2]
 [1 2 3]
 [2 3 4]]


'Here both var2 and var3 are broadcasted to some other shape'